version: '3.7'

services:
  api:
    build: .
    image: fleet:latest
    ports:
      - 4000:4000
    volumes:
      - .:/app
      - /app/_build/
      - /app/deps/
    environment:
      PGHOST: db
      PGPORT: 5432
      PGUSER: fleetdb
      PGPASSWORD: fleetdb
      PGDATABASE: fleetdb
    depends_on:
      - db

  db:
    image: postgis/postgis
    restart: always
    ports:
      - 54320:5432
    volumes:
      - ./docker/pgdata:/var/lib/postgresql
    environment:
      POSTGRES_DB: fleetdb
      POSTGRES_USER: fleetdb
      POSTGRES_PASSWORD: fleetdb
